### ISSUE TITLE
Using custom template files for subscription form and email templates

### ISSUE THREAD

**Issue by FlorentinBulotAQ** [YunoHost-Apps/listmonk_ynh#32]
Hello,

I have installed listmonk on a yunohost server using the yunohost GUI on a VPN hosted by Hetzner, with the following versions:
```
yunohost:
  repo: stable
  version: 11.1.15
yunohost-admin:
  repo: stable
  version: 11.1.8
moulinette:
  repo: stable
  version: 11.1.4
ssowat:
  repo: stable
  version: 11.1.4
```

I want to use a custom subscription form template. 

I cannot find the location of the files for this subscription form. In `/var/www/listmonk`, I have the following files:
`
```shell
total 16M
drwxr-x---   3 listmonk www-data 4.0K May  2 21:19 .
drwxr-xr-x+ 12 root     root     4.0K Apr 24 10:38 ..
-r--------   1 listmonk listmonk  878 Apr 24 10:38 config.toml
-rw-r-----   1 listmonk www-data  34K Mar 20 14:48 LICENSE
-rwxr-x--x   1 listmonk www-data  16M Mar 20 14:51 listmonk
-rw-r-----   1 listmonk www-data 2.4K Mar 20 14:48 README.md
``` 

I have tried to look for the files using `find / -name "subscription"` but nothing comes up in the results.

I have tried to follow this tutorial: https://yasoob.me/posts/setting-up-listmonk-opensource-newsletter-mailing/ , I went to `/home/USERNAME/listmonk`, copied the static directory and changed the `docker-compose.yml` file as described in the tutorial but then running `docker-compose up --force-recreate -d app` gives me `bash: docker-compose: command not found`

How can you create a custom subscription form?

Thank you very much for your help and for your time,
Best wishes,
Florentin.
